version: '3'
services:
  ship-postgres:
    container_name: eosio-history-postgres
    build:
        dockerfile: Dockerfile
        context: ./postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres/conf/postgresql.conf:/tmp/postgresql.conf
      - ./postgres/${POSTGRES_VOLUME}:/var/lib/postgresql/data/pgdata
  ship-pgadmin:
    image: dpage/pgadmin4
    container_name: eosio-history-pgadmin
    depends_on:
      - ship-postgres
    ports:
      - "${PGADMIN_PORT}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}